# .github/workflows/publish-to-npm.yml

name: Publish Package to npm

on:
  push:
    branches:
      - main
    #paths:
      #- 'src/**'
      #- 'package.json'

permissions:
  contents: write
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'
          scope: "@hsm-sanosoft"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest   # o la versión que prefieras

      - name: Install dependencies
        run: pnpm install
        # opcional: usa cache integrada si quieres acelerar
        # env:
        #   PNPM_HOME: ~/.local/share/pnpm

      - name: Build package
        run: pnpm build

      - name: Bump version & tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          VERSION=$(npm version patch -m "chore(release): %s")
          git push origin main --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

