# .github/workflows/publish-to-npm.yml

name: Publish Package to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'
          scope: "@hsm-sanosoft"
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install
        
      - name: Generate indexes
        run: pnpm generateIndexes

      - name: Build package
        run: pnpm build

      - name: Tag release from package.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          NEW_VER=$(npm version patch --no-git-tag-version)
          git add .
          git commit -m "release: bump to $NEW_VER and update generated indexes"
          git tag "v$NEW_VER"
          git push origin main --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  
      - name: Prepackage
        run: pnpm prePackage

      - name: Publish to npm
        run: npm publish dist/ --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
