# .github/workflows/publish-to-npm.yml

name: Publish Package to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'
          scope: "@hsm-sanosoft"
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      # --- NEW: Tag the current commit based on package.json ---
      - name: Tag release from package.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          bash scripts/generate-index.sh
          if ! git diff --quiet; then
            git add .
            git commit -m "ci: update generated files (models/entities/index.ts)"
            COMMIT=$(git rev-parse HEAD)
            VER=$(node -p "require('./package.json').version")
            TAG="v$VER"
            git tag "$TAG" "$COMMIT"
            git push origin "$TAG"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
