# .github/workflows/publish-to-npm.yml

name: Publish Package to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'
          scope: "@hsm-sanosoft"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      - name: Clean workspace for version bump
        run: |
          # descarta cambios en tracked files
          git reset --hard HEAD
          # elimina archivos/carpetas no trackeados (dist/, node_modules/, etc.)
          git clean -fd

      - name: Bump version & tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # esto crea el commit y el tag
          npm version patch -m "chore(release): %s"
          git push origin main --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
