# .github/workflows/publish-to-npm.yml

name: Publish Package to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      - name: Bump version in package.json (no commit, no tag)
        run: |
          # Esto actualizará package.json solo localmente
          npm version patch --no-git-tag-version

      - name: Read new version
        id: ver
        run: |
          echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - name: Tag git with v${{ steps.ver.outputs.VERSION }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ steps.ver.outputs.VERSION }}" -m "chore(release): v${{ steps.ver.outputs.VERSION }}"
          git push origin "v${{ steps.ver.outputs.VERSION }}"

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}